name: Simple Artifact Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create a test file
        run: echo "test" > test.txt
      - name: Upload test artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: test.txt
